name: GuildsRPG
author: [Tethered_ & NeuroBinds Project]
description: A Plugin For Easily Managing Guilds
version: 1.3.2
main: GuildsRPG\GCore
api:
- 2.0.0
commands:
  guilds:
    description: use /guilds help for all parameters
    permission: guilds.command
  g:
    description: use /guilds help for all parameters
    permission: guilds.command
permissions:
  guilds.command:
    default: true
    description: "Allow use of all guilds commands"
